################################################################################
#
# Build for multi files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
dir := ${ENV_PATH_ROOT}/embed

include $(ENV_PATH_ROOT)/build/buildmulti.mk
