################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
BUILD =e

c_objects = wdt_test.o
CFLAGS = -lm
run_dist =$(BUILD_NFS_PATH)/home/sys/modules

# This is the file name of the executables and path where 
# place the executables
buildout = wdt_test

include $(ENV_PATH_ROOT)/build/buildrules.mk