################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
obj-m := kernel_bus_i2c.o
FIRMWARE_CLEAN := 1

include $(ENV_PATH_ROOT)/build/buildmod.mk