#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/usr/lib
export PATH LD_LIBRARY_PATH

mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

#local ip support 127.0.0.1
ifconfig lo up
ifconfig lo netmask 255.255.255.0

#insmod for system
for module in /home/sys/modules/*.ko; do
    insmod ${module}
done

#start all application

