################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
BUILD =e

c_objects = ap_i2c_test.o

# This is the file name of the executables and path where 
# place the executables
buildout = ap_i2c_test

include $(ENV_PATH_ROOT)/build/buildrules.mk