BUILD?=s

CCFLAGS:=-O3 -std=c++17 -fno-strict-aliasing -lrt

INCLUDES=-I include/

buildout=libjsoncpp

cpp_objects=json_reader.o \
			json_value.o \
			json_writer.o

include $(ENV_PATH_ROOT)/build/buildrules.mk
