################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################

MODULE_NAME := kernalout
obj-m := ${MODULE_NAME}.o
${MODULE_NAME}-objs := kernel_main.o kernel_base.o
FIRMWARE_CLEAN := 1

include $(ENV_PATH_ROOT)/build/buildmod.mk