@startuml
frame 登陆页
frame 微信扫码页
frame 首页 {
    frame 首页头像弹窗 {
        frame "绑定/解绑" 
        note right {
            （支持微信号及手机号的绑定与解绑）
        }
        frame "修改密码"
        frame "退出登陆"
    }
}
 
frame 修改密码页
登陆页 -right-> 首页:手机号/账号 + 密码登陆
登陆页 -down-> 微信扫码页:微信扫码登陆
 
微信扫码页 --> 首页
修改密码 -up-> 修改密码页
修改密码页 -up-> 登陆页
退出登陆 -up-> 登陆页
 
@enduml