################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
obj-m := relay.o
FIRMWARE_CLEAN := 1
KBUILD_EXTRA_SYMBOLS = $(ENV_PATH_ROOT)/mod/x1.relay/export/Module.symvers

include $(ENV_PATH_ROOT)/build/buildmod.mk